name: Upload Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  package-and-deploy:
    name: ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "{{ matrix.python_version }}"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    - name: Build & publish package
        poetry publish --build
